// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwrsawktbskghejtoynn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cnNhd2t0YnNrZ2hlanRveW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODY0NTgsImV4cCI6MjA2NDU2MjQ1OH0.7hFauXXB8wJMrenP5KXgL_4fg5jyK9ET0E7mkanUNyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);